/**
 * Orchestration plan application logic.  Extracted from
 * orchestration-manager.ts to stay within the 500-line file limit.
 */

import { getBackend } from "@/lib/backend-instance";
import type { CreateBeatInput, UpdateBeatInput } from "@/lib/backend-port";
import {
  ORCHESTRATION_WAVE_LABEL,
  allocateWaveSlug,
  buildWaveSlugLabel,
  buildWaveTitle,
  extractWaveSlug,
  isLegacyNumericWaveSlug,
} from "@/lib/wave-slugs";
import type {
  ApplyOrchestrationOverrides,
  ApplyOrchestrationResult,
  Beat,
  OrchestrationAgentSpec,
  OrchestrationWave,
} from "@/lib/types";

import {
  type OrchestrationSessionEntry,
  sessions,
} from "@/lib/orchestration-internals";

// ── Private helpers ─────────────────────────────────────────────────

function formatAgentPlan(agents: OrchestrationAgentSpec[]): string {
  if (agents.length === 0) return "- 1 x generalist";
  return agents
    .map((agent) => {
      const specialty = agent.specialty ? ` (${agent.specialty})` : "";
      return `- ${agent.count} x ${agent.role}${specialty}`;
    })
    .join("\n");
}

function countActiveChildrenByParent(
  beats: Beat[]
): Map<string, number> {
  const counts = new Map<string, number>();
  for (const beat of beats) {
    if (!beat.parent || beat.state === "closed") continue;
    counts.set(beat.parent, (counts.get(beat.parent) ?? 0) + 1);
  }
  return counts;
}

function isOpenOrchestratedWave(beat: Beat | undefined): boolean {
  if (!beat) return false;
  if (beat.state === "closed") return false;
  return beat.labels?.includes(ORCHESTRATION_WAVE_LABEL) ?? false;
}

function isMissingDependencyError(error?: string): boolean {
  if (!error) return false;
  return /not found|no dependency|does not exist|doesn't exist|no such/i.test(
    error
  );
}

function buildWaveDescription(
  sessionId: string,
  wave: OrchestrationWave,
  validChildren: Array<{ id: string; title: string }>,
  assumptions: string[],
): string {
  return [
    `Generated by orchestration session ${sessionId}.`,
    "",
    `Objective: ${wave.objective}`,
    "",
    "Agent plan:",
    formatAgentPlan(wave.agents),
    "",
    "Assigned beats:",
    ...validChildren.map((beat) => `- ${beat.id}: ${beat.title}`),
    wave.notes ? "" : null,
    wave.notes ? `Notes: ${wave.notes}` : null,
    assumptions.length > 0 ? "" : null,
    assumptions.length > 0 ? "Assumptions:" : null,
    ...assumptions.map((assumption) => `- ${assumption}`),
  ]
    .filter((line): line is string => Boolean(line))
    .join("\n");
}

async function reparentChild(
  child: { id: string; title: string },
  waveId: string,
  entry: OrchestrationSessionEntry,
  repoPath: string,
) {
  const currentParentId = entry.allBeats.get(child.id)?.parent;

  const updateResult = await getBackend().update(
    child.id,
    { parent: waveId } as UpdateBeatInput,
    repoPath,
  );
  if (!updateResult.ok) {
    throw new Error(
      updateResult.error?.message ??
        `Failed to reparent ${child.id}`
    );
  }

  const refreshed = await getBackend().get(child.id, repoPath);
  if (!refreshed.ok || refreshed.data?.parent !== waveId) {
    throw new Error(
      `Failed to confirm ${child.id} parent relationship to ${waveId}`
    );
  }

  const existingChild = entry.allBeats.get(child.id);
  if (existingChild) {
    entry.allBeats.set(child.id, {
      ...existingChild,
      parent: waveId,
    });
  }

  // Prune old wave->child edge if present.
  if (currentParentId && currentParentId !== waveId) {
    const removeResult = await getBackend().removeDependency(
      currentParentId,
      child.id,
      repoPath,
    );
    if (
      !removeResult.ok &&
      !isMissingDependencyError(removeResult.error?.message)
    ) {
      throw new Error(
        removeResult.error?.message ??
          `Failed to remove dependency ` +
          `${currentParentId} -> ${child.id}`
      );
    }
  }

  const relationDep = await getBackend().addDependency(
    waveId,
    child.id,
    repoPath,
  );
  if (
    !relationDep.ok &&
    !/already exists|duplicate|exists/i.test(
      relationDep.error?.message ?? ""
    )
  ) {
    throw new Error(
      relationDep.error?.message ??
        `Failed to link scene ${waveId} to ${child.id}`
    );
  }

  return currentParentId;
}

async function closeEmptiedSourceWaves(
  sourceParentIds: Set<string>,
  createdWaveIds: Set<string>,
  sessionId: string,
  repoPath: string,
) {
  const refreshed = await getBackend().list(undefined, repoPath);
  if (!refreshed.ok || !refreshed.data) {
    throw new Error(
      refreshed.error?.message ??
        "Failed to refresh beats before closing " +
        "rewritten source scenes"
    );
  }

  const beatsById = new Map(
    refreshed.data.map((beat) => [beat.id, beat])
  );
  const activeChildCounts = countActiveChildrenByParent(
    refreshed.data
  );

  for (const parentId of sourceParentIds) {
    if (createdWaveIds.has(parentId)) continue;

    const parent = beatsById.get(parentId);
    if (!isOpenOrchestratedWave(parent)) continue;

    const activeChildren =
      activeChildCounts.get(parentId) ?? 0;
    if (activeChildren > 0) continue;

    const closeResult = await getBackend().close(
      parentId,
      `Rewritten by orchestration session ${sessionId}`,
      repoPath,
    );
    if (!closeResult.ok) {
      throw new Error(
        closeResult.error?.message ??
          `Failed to close emptied source scene ${parentId}`
      );
    }
  }
}

// ── Per-wave processing ─────────────────────────────────────────────

interface WaveProcessingContext {
  sessionId: string;
  repoPath: string;
  entry: OrchestrationSessionEntry;
  plan: import("@/lib/types").OrchestrationPlan;
  overrides?: ApplyOrchestrationOverrides;
  usedWaveSlugs: Set<string>;
  sourceParentIds: Set<string>;
  createdWaveIds: Set<string>;
}

function computeWavePriority(
  validChildren: Array<{ id: string; title: string }>,
  allBeats: Map<string, Beat>,
): Beat["priority"] {
  let wavePriority: Beat["priority"] = 2;
  let hasPriority = false;
  for (const beat of validChildren) {
    const priority = allBeats.get(beat.id)?.priority;
    if (priority === undefined) continue;
    if (!hasPriority || priority < wavePriority) {
      wavePriority = priority;
      hasPriority = true;
    }
  }
  return wavePriority;
}

async function processWave(
  wave: OrchestrationWave,
  ctx: WaveProcessingContext,
  previousWaveId: string | null,
): Promise<{
  applied: ApplyOrchestrationResult["applied"][number];
  waveId: string;
} | null> {
  const validChildren = wave.beats.filter((beat) =>
    ctx.entry.allBeats.has(beat.id),
  );
  if (validChildren.length === 0) return null;

  const wavePriority = computeWavePriority(
    validChildren,
    ctx.entry.allBeats,
  );

  const description = buildWaveDescription(
    ctx.sessionId,
    wave,
    validChildren,
    ctx.plan.assumptions,
  );

  const waveIndexKey = String(wave.waveIndex);
  const overriddenName =
    ctx.overrides?.waveNames?.[waveIndexKey]?.trim();
  const waveName = overriddenName || wave.name;
  const overrideSlug =
    ctx.overrides?.waveSlugs?.[waveIndexKey];
  const waveSlug = allocateWaveSlug(
    ctx.usedWaveSlugs,
    overrideSlug,
  );
  const waveTitle = buildWaveTitle(waveSlug, waveName);

  const createResult = await getBackend().create(
    {
      title: waveTitle,
      type: "epic",
      priority: wavePriority,
      labels: [
        ORCHESTRATION_WAVE_LABEL,
        buildWaveSlugLabel(waveSlug),
      ],
      description,
    } as CreateBeatInput,
    ctx.repoPath,
  );

  if (!createResult.ok || !createResult.data?.id) {
    throw new Error(
      createResult.error?.message ??
        `Failed to create scene ${wave.waveIndex}`,
    );
  }

  const waveId = createResult.data.id;
  ctx.createdWaveIds.add(waveId);

  for (const child of validChildren) {
    const currentParentId = await reparentChild(
      child,
      waveId,
      ctx.entry,
      ctx.repoPath,
    );
    if (currentParentId) {
      ctx.sourceParentIds.add(currentParentId);
    }
  }

  if (previousWaveId) {
    const depResult = await getBackend().addDependency(
      previousWaveId,
      waveId,
      ctx.repoPath,
    );
    if (!depResult.ok) {
      throw new Error(
        depResult.error?.message ??
          `Failed to link scenes ` +
          `${previousWaveId} -> ${waveId}`,
      );
    }
  }

  return {
    waveId,
    applied: {
      waveIndex: wave.waveIndex,
      waveId,
      waveSlug,
      waveTitle,
      childCount: validChildren.length,
      children: validChildren.map((child) => ({
        id: child.id,
        title: child.title,
      })),
    },
  };
}

// ── applyOrchestrationSession ───────────────────────────────────────

export async function applyOrchestrationSession(
  sessionId: string,
  repoPath: string,
  overrides?: ApplyOrchestrationOverrides,
): Promise<ApplyOrchestrationResult> {
  const entry = sessions.get(sessionId);
  if (!entry) {
    throw new Error("Orchestration session not found");
  }
  if (!entry.session.plan) {
    throw new Error(
      "No orchestration plan available to apply",
    );
  }

  const plan = entry.session.plan;
  const applied: ApplyOrchestrationResult["applied"] = [];
  const skipped: string[] = [];

  const existing = await getBackend().list(
    undefined,
    repoPath,
  );
  if (!existing.ok || !existing.data) {
    throw new Error(
      existing.error?.message ??
        "Failed to load existing scenes",
    );
  }
  const usedWaveSlugs = new Set<string>();
  for (const beat of existing.data) {
    if (!beat.labels?.includes(ORCHESTRATION_WAVE_LABEL)) {
      continue;
    }
    const slug = extractWaveSlug(beat.labels);
    if (!slug || isLegacyNumericWaveSlug(slug)) continue;
    usedWaveSlugs.add(slug);
  }

  const ctx: WaveProcessingContext = {
    sessionId,
    repoPath,
    entry,
    plan,
    overrides,
    usedWaveSlugs,
    sourceParentIds: new Set<string>(),
    createdWaveIds: new Set<string>(),
  };

  let previousWaveId: string | null = null;
  const sortedWaves = plan.waves
    .slice()
    .sort((a, b) => a.waveIndex - b.waveIndex);

  for (const wave of sortedWaves) {
    const result = await processWave(
      wave,
      ctx,
      previousWaveId,
    );
    if (!result) {
      skipped.push(`wave:${wave.waveIndex}`);
      continue;
    }
    previousWaveId = result.waveId;
    applied.push(result.applied);
  }

  if (ctx.sourceParentIds.size > 0) {
    await closeEmptiedSourceWaves(
      ctx.sourceParentIds,
      ctx.createdWaveIds,
      sessionId,
      repoPath,
    );
  }

  return { applied, skipped };
}
